### ISSUE TITLE
No permission to write memory

### ISSUE THREAD

**Issue by nonunknown** [dedobbin/mem_hengst#1]
I've tried example.cpp

compile it with `sudo make example`
then tried` chmod -R a+rwx . and chmod -R 777 ./example`

and still got this error:
![Screenshot from 2020-07-05 18-49-21](https://user-images.githubusercontent.com/58845030/86542930-77d38200-bef0-11ea-9ded-721fba5410fc.png)

**Comment by dedobbin** [comment]
Ah, it's not the executable that has no permission, it's just that the memory you write to is read only. You can see it in the permission flags in screenshot you provided.
